### ISSUE TITLE
The alien function "enchant_broker_init" is undefined.

### ISSUE THREAD

**Issue by guojing0** [tlikonen/cl-enchant#1]
Hi,

Recently I am playing with your library and really enjoy it. It worked well some days ago, and today I use Quicklisp to load and try some examples from the README, SBCL displays this. How can I resolve it? Thank you.

Update: After loading `enchant-autoload` everything is fine. So I was wondering that do I have to load `enchant-autoload` everytime?

```
* (enchant:with-dict (lang "en_US")            (enchant:dict-suggest lang "wrking"))

debugger invoked on a SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR @52A005D7 in thread
#<THREAD "main thread" RUNNING {1004E18143}>:
  The alien function "enchant_broker_init" is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

("undefined function")
```

**Comment by tlikonen** [comment]
That's right. Only the `enchant-autoload` system loads the library. Thanks for the report anyway. I noticed that in Debian Linux the Enchant library file is named `libenchant-2.so.2` and I needed to update my library loading definition a bit.
